### ISSUE TITLE
バッテリー表示が正確ではない

### ISSUE THREAD

**Issue by GS-Bacon** [GS-Bacon/bacon-memento#2]
そもそもADCの読み取り値が結構怪しいが、丸めてやることである程度使える

それよりも残量70%くらいで電源が落ちてしまうのでどこまでがほんとに使える残量なのかがわからない

**Comment by miminashi** [comment]
LiPoの残容量を電圧だけで判断するのがそもそも結構難しい（最後まで電圧がフラットなので）
ちゃんとやるならラップトップやスマホみたいに出入りした電荷と充放電回数を記録してくれるコントローラを使うことだけど、そもそもそういうコントローラ載ってないとどうしようもない

電池電圧がどういうカーブを描くか実験で調べておいて、どこにライン引くか決める、くらいならできるかも

**Comment by GS-Bacon** [comment]
電池電圧を調べた
最大電圧とディスプレイが正しく表示できなくなるまでの電圧の間を範囲として電圧を正規化したものを大雑把なバッテリー残量とするとことで解決にする
Adafruit からそれっぽいモジュールが別売りされてるので気になったら試してみる
